version: '3.8'

services:
  cms:
    build: ./backend
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    ports:
      - "8000:8000"
  
  admin:
    build: ./frontend
    environment:
      - VITE_CMS_API=http://cms:8000
    ports:
      - "3000:3000"
    depends_on:
      - cms 